import About from "./components/About";
import Connect from "./components/Connect";
import Projects from "./components/Projects";
import ShortIntro from "./components/ShortIntro";
import Timeline from "./components/Timeline";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div>
      <ShortIntro />
      <About />
      <Timeline />
      <Projects />
      <Connect />
    </div>
  );
}
